Create database custo_101;
use custo_101;
ALTER TABLE customer
RENAME COLUMN `purchase_amount_(usd)` TO purchase_amount_usd;
select * from customer;
select avg(purchase_amount_usd) from customer;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount_usd) AS total_purchase
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount_usd from 
customer
where discount_applied = 'Yes' and purchase_amount_usd>59.7644
group by customer_id,purchase_amount_usd;

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,round(avg(review_rating),2) from customer
group by item_purchased
order by avg(review_rating) desc limit 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,avg(purchase_amount_usd)
from customer
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
sum(purchase_amount_usd),
avg(purchase_amount_usd)
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select discount_applied,item_purchased,
count(item_purchased),
sum(purchase_amount_usd)
from customer
where discount_applied = 'yes'
group by discount_applied,item_purchased
order by count(item_purchased) desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id,previous_purchases,
CASE 
	when previous_purchases =1 then "New"
    when previous_purchases between 2 and 10
    then 'Returning'
    else 'Loyal'
    END as customer_segment
    from customer
    )
 select customer_segment,count(*) as "Number of Customers"
 from customer_type
 group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc)
as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,count(customer_id)
from customer
where previous_purchases>=5
group by subscription_status;



-- Q10. What is the revenue contribution of each age group?

select age_group,sum(purchase_amount_usd)
from customer
group by age_group;